### ISSUE TITLE
jupyter example issues a AttributeError: module 'pystare' has no attribute 'to_JulianTAI'  

### ISSUE THREAD

**Issue by mbauer288** [SpatioTemporal/pystareplotlib#2]
Step 1 Install pySTAREplotlib (https://github.com/SpatioTemporal/pystareplotlib)

    # Some dependencies 
        $ pip install descartes
        $ pip install pillow
        $ pip install pythreejs          
        
        $ cd
        $ gh repo clone skoch9/meshplot
        $ cd meshplot  
        $ python setup.py build_ext --inplace 
        $ pip install -e .
            Obtaining file:///home/mbauer/meshplot
                Preparing metadata (setup.py) ... done
            Installing collected packages: meshplot
                Running setup.py develop for meshplot
            Successfully installed meshplot-0.3.3        
            
    Step 1a: Clone pySTAREplotlib repo
        $ cd 
        $ gh repo clone SpatioTemporal/pystareplotlib
        $ cd pystareplotlib
           
    Step 1b: Install pySTAREplotlib (be sure pyevn mystare being used).
   	    $ python setup.py build_ext --inplace 
            running build_ext
            
        $ pip install -e .      
            Installing collected packages: pystareplotlib
                Running setup.py develop for pystareplotlib
                Successfully installed pystareplotlib-0.1.0

        This creates
            /home/mbauer/.pyenv/versions/mystare/lib/python3.10/site-packages/pystareplotlib.egg-link
         
        $ cd examples
        $ jupyter notebook  
            08-Pystareplotlib-1.ipynb          ## NEEDS FIX?
                ----> 7     sp = stare_prism(siv=siv
                      8                      ,tiv=numpy.array([0x1f484ade232b1b6d],dtype=numpy.int64)
                      9                      ,color=mpl.colors.rgb2hex([0,0,1])
                     10                     )
                --> 436     t_triple = pystare.to_JulianTAI(triple)
                    AttributeError: module 'pystare' has no attribute 'to_JulianTAI'

**Comment by michaelleerilee** [comment]
The API has gone from this

`t_triple = pystare.to_JulianTAI(triple)`

to this

`t_triple = pystare.to_julian_date(triple,'tai')`

Sorry about the problem.

**Comment by michaelleerilee** [comment]
Fixed in https://github.com/SpatioTemporal/pystareplotlib/releases/tag/v1.1.6
